from pathlib import Path
import re

# schema
p=Path('worker/schema.sql'); s=p.read_text()
if 'CREATE TABLE IF NOT EXISTS site_ads' not in s:
    s += '''\n\n-- Homepage advertisements\nCREATE TABLE IF NOT EXISTS site_ads (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  title TEXT,\n  image_key TEXT NOT NULL,\n  mime TEXT NOT NULL,\n  link_url TEXT,\n  active INTEGER NOT NULL DEFAULT 1,\n  sort_order INTEGER NOT NULL DEFAULT 0,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  updated_at TEXT NOT NULL DEFAULT (datetime('now'))\n);\nCREATE INDEX IF NOT EXISTS idx_site_ads_active_sort ON site_ads (active, sort_order, id);\n'''
    p.write_text(s)

# worker media handler
Path('worker/src/handlers/media.js').write_text(r'''const TYPES = new Set(["image/jpeg","image/png","image/webp","image/gif"]);
const MAX = 8*1024*1024;
function validate(file){if(!file||typeof file.arrayBuffer!=="function")throw new Error("Image file is required");if(!TYPES.has(file.type))throw new Error("Use JPG, PNG, WebP or GIF");if(file.size>MAX)throw new Error("Image must be 8 MB or smaller");}
function name(v="image"){return String(v).toLowerCase().replace(/[^a-z0-9._-]+/g,"-").replace(/^-+|-+$/g,"")||"image";}
async function put(env,file,prefix){validate(file);const key=`${prefix}/${crypto.randomUUID()}-${name(file.name)}`;await env.FILES.put(key,await file.arrayBuffer(),{httpMetadata:{contentType:file.type,cacheControl:"public, max-age=31536000, immutable"}});return key;}
export async function listPublicAds(request,env){const {results=[]}=await env.DB.prepare("SELECT id,title,link_url,sort_order,updated_at FROM site_ads WHERE active=1 ORDER BY sort_order ASC,id DESC").all();const origin=new URL(request.url).origin;return results.map(r=>({...r,image_url:`${origin}/media/ads/${r.id}`}));}
export async function serveAd(request,env,id){const row=await env.DB.prepare("SELECT image_key,mime FROM site_ads WHERE id=? LIMIT 1").bind(id).first();if(!row)return new Response("Not Found",{status:404});const obj=await env.FILES.get(row.image_key);if(!obj)return new Response("Not Found",{status:404});const h=new Headers();obj.writeHttpMetadata(h);h.set("Content-Type",row.mime||h.get("Content-Type")||"application/octet-stream");h.set("Cache-Control","public, max-age=3600, stale-while-revalidate=86400");h.set("Access-Control-Allow-Origin","*");return new Response(obj.body,{headers:h});}
export async function listAdminAds(request,env){const {results=[]}=await env.DB.prepare("SELECT id,title,image_key,mime,link_url,active,sort_order,created_at,updated_at FROM site_ads ORDER BY sort_order ASC,id DESC").all();const origin=new URL(request.url).origin;return results.map(r=>({...r,image_url:`${origin}/media/ads/${r.id}`}));}
export async function uploadOg(request,env){const f=await request.formData();const page=String(f.get("page")||"").trim().toLowerCase();const file=f.get("file");if(!/^[a-z0-9/_-]{1,80}$/.test(page))throw new Error("Invalid OG page key");const old=await env.DB.prepare("SELECT image_key FROM site_og_images WHERE page=? LIMIT 1").bind(page).first();const key=await put(env,file,`og/${page}`);await env.DB.prepare(`INSERT INTO site_og_images(page,image_key,mime,updated_at) VALUES(?,?,?,datetime('now')) ON CONFLICT(page) DO UPDATE SET image_key=excluded.image_key,mime=excluded.mime,updated_at=datetime('now')`).bind(page,key,file.type).run();if(old?.image_key&&old.image_key!==key)await env.FILES.delete(old.image_key).catch(()=>{});return {ok:true,page,image_key:key,mime:file.type};}
export async function uploadAd(request,env){const f=await request.formData();const file=f.get("file");const title=String(f.get("title")||"").trim().slice(0,160)||null;const link=String(f.get("link_url")||"").trim().slice(0,1500)||null;if(link&&!/^https?:\/\//i.test(link))throw new Error("Link must start with http:// or https://");const active=String(f.get("active")||"1")==="0"?0:1;const order=parseInt(String(f.get("sort_order")||"0"),10)||0;const key=await put(env,file,"ads/home");const r=await env.DB.prepare("INSERT INTO site_ads(title,image_key,mime,link_url,active,sort_order) VALUES(?,?,?,?,?,?)").bind(title,key,file.type,link,active,order).run();return {ok:true,id:r.meta?.last_row_id};}
export async function updateAd(request,env,id){const b=await request.json();const title=String(b.title||"").trim().slice(0,160)||null;const link=String(b.link_url||"").trim().slice(0,1500)||null;if(link&&!/^https?:\/\//i.test(link))throw new Error("Link must start with http:// or https://");await env.DB.prepare("UPDATE site_ads SET title=?,link_url=?,active=?,sort_order=?,updated_at=datetime('now') WHERE id=?").bind(title,link,b.active?1:0,parseInt(String(b.sort_order||0),10)||0,id).run();return {ok:true};}
export async function deleteAd(request,env,id){const row=await env.DB.prepare("SELECT image_key FROM site_ads WHERE id=? LIMIT 1").bind(id).first();if(!row)return {ok:true};await env.DB.prepare("DELETE FROM site_ads WHERE id=?").bind(id).run();await env.FILES.delete(row.image_key).catch(()=>{});return {ok:true};}
''')

# router
p=Path('worker/src/index.js'); t=p.read_text()
imp='import { listPublicAds, serveAd, listAdminAds, uploadOg, uploadAd, updateAd, deleteAd } from "./handlers/media.js";'
if imp not in t:t=t.replace('import { getOgImage, listOgImages, upsertOgImage } from "./handlers/og.js";','import { getOgImage, listOgImages, upsertOgImage } from "./handlers/og.js";\n'+imp)
if 'pathname === "/ads"' not in t:t=t.replace('      if (pathname.startsWith("/files/") && request.method === "GET") {','      if (pathname === "/ads" && request.method === "GET") return json(request, env, await listPublicAds(request, env));\n      const adMediaMatch = pathname.match(/^\\/media\\/ads\\/(\\d+)$/);\n      if (adMediaMatch && request.method === "GET") return await serveAd(request, env, adMediaMatch[1]);\n\n      if (pathname.startsWith("/files/") && request.method === "GET") {')
anchor='        if (pathname === "/admin/og-images" && request.method === "POST") return json(request, env, await upsertOgImage(request, env));'
if 'pathname === "/admin/media/og/upload"' not in t:
    t=t.replace(anchor,anchor+'\n        if (pathname === "/admin/media/og/upload" && request.method === "POST") return json(request, env, await uploadOg(request, env));\n        if (pathname === "/admin/media/ads" && request.method === "GET") return json(request, env, await listAdminAds(request, env));\n        if (pathname === "/admin/media/ads" && request.method === "POST") return json(request, env, await uploadAd(request, env));\n        const adminAdMatch = pathname.match(/^\\/admin\\/media\\/ads\\/(\\d+)$/);\n        if (adminAdMatch && request.method === "PUT") return json(request, env, await updateAd(request, env, adminAdMatch[1]));\n        if (adminAdMatch && request.method === "DELETE") return json(request, env, await deleteAd(request, env, adminAdMatch[1]));')
p.write_text(t)

# admin html
p=Path('admin.html'); h=p.read_text()
nav='<button class="nav-item" data-view="admins"><i class="fa-solid fa-user-shield"></i><span class="sidebar-label">จัดการแอดมิน</span></button>'
if 'data-view="media"' not in h:h=h.replace(nav,'<button class="nav-item" data-view="media"><i class="fa-solid fa-photo-film"></i><span class="sidebar-label">สื่อเว็บไซต์</span></button>\n                        '+nav)
if 'id="view-media"' not in h:
    view='''                    <!-- WEBSITE MEDIA -->\n                    <section class="view" id="view-media">\n                      <div class="view-header"><div><div class="view-title">สื่อเว็บไซต์</div><div class="view-desc">จัดการ Open Graph และรูปโฆษณาหน้าหลัก</div></div></div>\n                      <div class="media-admin-grid">\n                        <div class="admin-card"><div class="admin-card-title">Open Graph Image</div><div class="admin-card-desc">รูปเมื่อแชร์ลิงก์ · แนะนำ 1200×630 px</div><form id="ogUploadForm" class="media-upload-form"><select class="admin-select" name="page"><option value="home">หน้าหลัก</option><option value="checkup">บันทึกกิจกรรม</option><option value="card">บัตรนักศึกษา</option><option value="sys">Token Key</option></select><input class="admin-input" name="file" type="file" accept="image/jpeg,image/png,image/webp,image/gif" required><div class="media-help">JPG, PNG, WebP, GIF · สูงสุด 8 MB</div><button class="admin-btn primary" type="submit"><i class="fa-solid fa-cloud-arrow-up"></i> อัปโหลด / แทนที่</button></form><div id="ogMediaList" class="media-list"></div></div>\n                        <div class="admin-card"><div class="admin-card-title">โฆษณา / ประกาศหน้าหลัก</div><div class="admin-card-desc">รูปที่เปิดใช้งานจะแสดงใน Slider หน้าหลัก</div><form id="adUploadForm" class="media-upload-form"><input class="admin-input" name="title" placeholder="ชื่อ/คำอธิบาย"><input class="admin-input" name="link_url" type="url" placeholder="ลิงก์เมื่อคลิก (ไม่บังคับ)"><div class="admin-row"><input class="admin-input" name="sort_order" type="number" value="0"><label class="media-check"><input name="active" type="checkbox" checked> แสดง</label></div><input class="admin-input" name="file" type="file" accept="image/jpeg,image/png,image/webp,image/gif" required><div class="media-help">JPG, PNG, WebP, GIF · สูงสุด 8 MB</div><button class="admin-btn primary" type="submit"><i class="fa-solid fa-cloud-arrow-up"></i> เพิ่มรูป</button></form><div id="adMediaList" class="media-list"></div></div>\n                      </div>\n                    </section>\n\n'''
    h=h.replace('                    <!-- ═══ ADMINS ═══ -->',view+'                    <!-- ═══ ADMINS ═══ -->')
p.write_text(h)

# admin js
p=Path('JavaScript/admin.js'); j=p.read_text()
if "{ view: 'media'" not in j:j=j.replace("{ view: 'admins', label: 'จัดการแอดมิน', icon: 'fa-user-shield' }","{ view: 'media', label: 'สื่อเว็บไซต์', icon: 'fa-photo-film' },\n    { view: 'admins', label: 'จัดการแอดมิน', icon: 'fa-user-shield' }")
if "if (view === 'media') loadMediaTab();" not in j:j=j.replace("    if (view === 'admins') loadAdminsTab();","    if (view === 'media') loadMediaTab();\n    if (view === 'admins') loadAdminsTab();")
if '/* WEBSITE MEDIA MANAGER */' not in j:
    j += r'''

/* WEBSITE MEDIA MANAGER */
async function mediaJson(res){let d=null;try{d=await res.json()}catch(_){ }if(!res.ok)throw new Error(d?.details||d?.error||`HTTP ${res.status}`);return d}
async function mediaUpload(path,form){const token=await auth0Client.getTokenSilently();return mediaJson(await fetch(`${API_BASE_URL}${path}`,{method:'POST',headers:{Authorization:`Bearer ${token}`},body:form}))}
async function loadMediaTab(){try{const [o,a]=await Promise.all([adminFetch('/admin/og-images'),adminFetch('/admin/media/ads')]);renderOgMedia(await mediaJson(o));renderAds(await mediaJson(a))}catch(e){showToast(`โหลดสื่อไม่สำเร็จ: ${e.message}`,'error')}}
function renderOgMedia(rows=[]){const n={home:'หน้าหลัก',checkup:'บันทึกกิจกรรม',card:'บัตรนักศึกษา',sys:'Token Key'};document.getElementById('ogMediaList').innerHTML=rows.length?rows.map(r=>`<div class="media-row"><img src="${API_BASE_URL}/og/image?page=${encodeURIComponent(r.page)}&v=${encodeURIComponent(r.updated_at||'')}" alt=""><div class="media-row-main"><strong>${escHtmlAdmin(n[r.page]||r.page)}</strong><small>${escHtmlAdmin(r.image_key)}</small><small>${escHtmlAdmin(r.updated_at||'—')}</small></div></div>`).join(''):'<div class="dt-empty">ยังไม่มี OG image ในฐานข้อมูล</div>'}
function renderAds(rows=[]){document.getElementById('adMediaList').innerHTML=rows.length?rows.map(r=>`<div class="media-row"><img src="${escHtmlAdmin(r.image_url)}?v=${encodeURIComponent(r.updated_at||'')}" alt=""><div class="media-row-main"><strong>${escHtmlAdmin(r.title||`โฆษณา #${r.id}`)}</strong><small>${r.active?'กำลังแสดง':'ซ่อนอยู่'} · ลำดับ ${r.sort_order||0}</small><small>${escHtmlAdmin(r.link_url||'ไม่มีลิงก์')}</small></div><div class="media-row-actions"><button class="admin-btn sm" onclick='toggleAd(${r.id},${r.active?0:1},${r.sort_order||0},${JSON.stringify(r.title||'')},${JSON.stringify(r.link_url||'')})'>${r.active?'ซ่อน':'แสดง'}</button><button class="admin-btn sm danger" onclick="removeAd(${r.id})"><i class="fa-solid fa-trash"></i></button></div></div>`).join(''):'<div class="dt-empty">ยังไม่มีรูปโฆษณา</div>'}
document.getElementById('ogUploadForm')?.addEventListener('submit',async e=>{e.preventDefault();const b=e.currentTarget.querySelector('button');b.disabled=true;try{await mediaUpload('/admin/media/og/upload',new FormData(e.currentTarget));showToast('อัปโหลด OG image สำเร็จ','success');e.currentTarget.querySelector('[name=file]').value='';await loadMediaTab()}catch(x){showToast(x.message,'error')}finally{b.disabled=false}})
document.getElementById('adUploadForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,fd=new FormData(f),b=f.querySelector('button');fd.set('active',f.querySelector('[name=active]').checked?'1':'0');b.disabled=true;try{await mediaUpload('/admin/media/ads',fd);showToast('เพิ่มรูปโฆษณาสำเร็จ','success');f.reset();f.querySelector('[name=active]').checked=true;f.querySelector('[name=sort_order]').value='0';await loadMediaTab()}catch(x){showToast(x.message,'error')}finally{b.disabled=false}})
async function toggleAd(id,active,sort_order,title,link_url){try{await mediaJson(await adminFetch(`/admin/media/ads/${id}`,{method:'PUT',body:JSON.stringify({active:!!active,sort_order,title,link_url})}));await loadMediaTab()}catch(e){showToast(e.message,'error')}}
async function removeAd(id){if(!await confirmDialog({title:'ลบรูปโฆษณา',body:'รูปจะถูกลบจาก R2 และฐานข้อมูล',okText:'ลบรูป'}))return;try{await mediaJson(await adminFetch(`/admin/media/ads/${id}`,{method:'DELETE'}));showToast('ลบรูปแล้ว','success');await loadMediaTab()}catch(e){showToast(e.message,'error')}}
'''
p.write_text(j)

# admin css
p=Path('CSS/admin.css'); c=p.read_text()
if '/* WEBSITE MEDIA MANAGER */' not in c:
    c += '\n/* WEBSITE MEDIA MANAGER */\n.media-admin-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.media-upload-form,.media-list{display:flex;flex-direction:column;gap:10px}.media-upload-form{margin:16px 0 20px}.media-help{font-size:11.5px;color:var(--ink-50)}.media-check{display:flex;align-items:center;gap:7px;font-size:12.5px;font-weight:700}.media-row{display:grid;grid-template-columns:92px minmax(0,1fr) auto;align-items:center;gap:12px;padding:10px;border:1px solid var(--ink-15);border-radius:var(--r-md)}.media-row img{width:92px;height:58px;object-fit:cover;border-radius:var(--r-sm)}.media-row-main{display:flex;flex-direction:column;gap:2px;min-width:0}.media-row-main small{color:var(--ink-50);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.media-row-actions{display:flex;gap:6px}@media(max-width:900px){.media-admin-grid{grid-template-columns:1fr}}@media(max-width:600px){.media-row{grid-template-columns:76px minmax(0,1fr)}.media-row img{width:76px;height:52px}.media-row-actions{grid-column:1/-1;justify-content:flex-end}}\n'
p.write_text(c)

# homepage dynamic ads
p=Path('JavaScript/index.js'); q=p.read_text().replace("const slides = document.querySelectorAll('.slide');","let slides = document.querySelectorAll('.slide');")
if 'async function loadHomepageAds()' not in q:
    q=q.replace('            // Initialize Auth0 using central script','            loadHomepageAds();\n\n            // Initialize Auth0 using central script')
    q=q.replace('        // Slider functionality\n',r'''        async function loadHomepageAds(){try{const r=await fetch(`${API_BASE_URL}/ads`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const ads=await r.json();if(!Array.isArray(ads)||!ads.length)return;const slider=document.querySelector('.slider');slider.innerHTML=ads.map(ad=>{const alt=String(ad.title||'ประกาศ').replace(/"/g,'&quot;');const img=`<img src="${ad.image_url}" alt="${alt}" loading="lazy" decoding="async">`;return `<div class="slide">${ad.link_url?`<a href="${ad.link_url}" target="_blank" rel="noopener noreferrer sponsored">${img}</a>`:img}</div>`}).join('');slides=document.querySelectorAll('.slide');currentSlide=0;dotsContainer.innerHTML='';slides.forEach((_,i)=>{const d=document.createElement('span');d.classList.add('dot');if(i===0)d.classList.add('active');d.onclick=()=>goToSlide(i);dotsContainer.appendChild(d)});updateSlider();document.querySelectorAll('.slider-btn').forEach(b=>b.style.display=slides.length>1?'':'none');dotsContainer.style.display=slides.length>1?'':'none';resetInterval()}catch(e){console.warn('Homepage ads unavailable; using fallback slide',e)}}

        // Slider functionality
''')
p.write_text(q)

# cache bump
p=Path('service-worker.js'); w=p.read_text(); w=re.sub(r"const CACHE_NAME = 'sorasukt-pwa-v(\d+)'",lambda m:f"const CACHE_NAME = 'sorasukt-pwa-v{int(m.group(1))+1}'",w,count=1);p.write_text(w)
