const TYPES = new Set(["image/jpeg","image/png","image/webp","image/gif"]);
const MAX = 8*1024*1024;
function validate(file){if(!file||typeof file.arrayBuffer!=="function")throw new Error("Image file is required");if(!TYPES.has(file.type))throw new Error("Use JPG, PNG, WebP or GIF");if(file.size>MAX)throw new Error("Image must be 8 MB or smaller");}
function name(v="image"){return String(v).toLowerCase().replace(/[^a-z0-9._-]+/g,"-").replace(/^-+|-+$/g,"")||"image";}
async function put(env,file,prefix){validate(file);const key=`${prefix}/${crypto.randomUUID()}-${name(file.name)}`;await env.FILES.put(key,await file.arrayBuffer(),{httpMetadata:{contentType:file.type,cacheControl:"public, max-age=31536000, immutable"}});return key;}
export async function listPublicAds(request,env){const {results=[]}=await env.DB.prepare("SELECT id,title,link_url,sort_order,updated_at FROM site_ads WHERE active=1 ORDER BY sort_order ASC,id DESC").all();const origin=new URL(request.url).origin;return results.map(r=>({...r,image_url:`${origin}/media/ads/${r.id}`}));}
export async function serveAd(request,env,id){const row=await env.DB.prepare("SELECT image_key,mime FROM site_ads WHERE id=? LIMIT 1").bind(id).first();if(!row)return new Response("Not Found",{status:404});const obj=await env.FILES.get(row.image_key);if(!obj)return new Response("Not Found",{status:404});const h=new Headers();obj.writeHttpMetadata(h);h.set("Content-Type",row.mime||h.get("Content-Type")||"application/octet-stream");h.set("Cache-Control","public, max-age=3600, stale-while-revalidate=86400");h.set("Access-Control-Allow-Origin","*");return new Response(obj.body,{headers:h});}
export async function listAdminAds(request,env){const {results=[]}=await env.DB.prepare("SELECT id,title,image_key,mime,link_url,active,sort_order,created_at,updated_at FROM site_ads ORDER BY sort_order ASC,id DESC").all();const origin=new URL(request.url).origin;return results.map(r=>({...r,image_url:`${origin}/media/ads/${r.id}`}));}
export async function uploadOg(request,env){const f=await request.formData();const page=String(f.get("page")||"").trim().toLowerCase();const file=f.get("file");if(!/^[a-z0-9/_-]{1,80}$/.test(page))throw new Error("Invalid OG page key");const old=await env.DB.prepare("SELECT image_key FROM site_og_images WHERE page=? LIMIT 1").bind(page).first();const key=await put(env,file,`og/${page}`);await env.DB.prepare(`INSERT INTO site_og_images(page,image_key,mime,updated_at) VALUES(?,?,?,datetime('now')) ON CONFLICT(page) DO UPDATE SET image_key=excluded.image_key,mime=excluded.mime,updated_at=datetime('now')`).bind(page,key,file.type).run();if(old?.image_key&&old.image_key!==key)await env.FILES.delete(old.image_key).catch(()=>{});return {ok:true,page,image_key:key,mime:file.type};}
export async function uploadAd(request,env){const f=await request.formData();const file=f.get("file");const title=String(f.get("title")||"").trim().slice(0,160)||null;const link=String(f.get("link_url")||"").trim().slice(0,1500)||null;if(link&&!/^https?:\/\//i.test(link))throw new Error("Link must start with http:// or https://");const active=String(f.get("active")||"1")==="0"?0:1;const order=parseInt(String(f.get("sort_order")||"0"),10)||0;const key=await put(env,file,"ads/home");const r=await env.DB.prepare("INSERT INTO site_ads(title,image_key,mime,link_url,active,sort_order) VALUES(?,?,?,?,?,?)").bind(title,key,file.type,link,active,order).run();return {ok:true,id:r.meta?.last_row_id};}
export async function updateAd(request,env,id){const b=await request.json();const title=String(b.title||"").trim().slice(0,160)||null;const link=String(b.link_url||"").trim().slice(0,1500)||null;if(link&&!/^https?:\/\//i.test(link))throw new Error("Link must start with http:// or https://");await env.DB.prepare("UPDATE site_ads SET title=?,link_url=?,active=?,sort_order=?,updated_at=datetime('now') WHERE id=?").bind(title,link,b.active?1:0,parseInt(String(b.sort_order||0),10)||0,id).run();return {ok:true};}
export async function deleteAd(request,env,id){const row=await env.DB.prepare("SELECT image_key FROM site_ads WHERE id=? LIMIT 1").bind(id).first();if(!row)return {ok:true};await env.DB.prepare("DELETE FROM site_ads WHERE id=?").bind(id).run();await env.FILES.delete(row.image_key).catch(()=>{});return {ok:true};}
